from pathlib import Path
p=Path('app/src/main/java/com/bazaverse/arcanewaves/MainActivity.java')
s=p.read_text()

def rep(old,new,name):
    global s
    if old not in s:
        raise SystemExit(f'anchor missing: {name}')
    s=s.replace(old,new,1)

rep('''        float comboTimer = 0f;\n        boolean campRestUsed = false;''','''        float comboTimer = 0f;\n        float castVisualTimer = 0f;\n        int castVisualSpell = -1;\n        boolean campRestUsed = false;''','fields')
rep('''            hitFlash = Math.max(0f, hitFlash - dt * 3.0f);''','''            hitFlash = Math.max(0f, hitFlash - dt * 3.0f);\n            castVisualTimer = Math.max(0f, castVisualTimer - dt * 3.6f);''','timer')
rep('''            combo = 0; lastComboSpell = -1; comboTimer = 0f;''','''            combo = 0; lastComboSpell = -1; comboTimer = 0f; castVisualTimer = 0f; castVisualSpell = -1;''','reset')
rep('''            lastComboSpell = sid;\n            comboTimer = 2.8f;''','''            lastComboSpell = sid;\n            comboTimer = 2.8f;\n            castVisualSpell = sid;\n            castVisualTimer = 1f;''','cast visual')
rep('''            drawHero(c, px, py, 1.0f, roster[selectedCharacter].female);\n            drawParticles(c);''','''            drawHero(c, px, py, 1.0f, roster[selectedCharacter].female);\n            if (castVisualTimer > 0f && castVisualSpell >= 0) drawCastSigil(c, px, py, castVisualSpell, castVisualTimer);\n            drawParticles(c);''','battle sigil')
rep('''                drawGlowOrb(c, x + 22f, y + 22f, 9f, withAlpha(base, 220));\n                text(c, spellNames[i], x + 40f, y + 30f, 17f, Color.WHITE, Paint.Align.LEFT, true);''','''                drawGlowOrb(c, x + 22f, y + 22f, 11f, withAlpha(base, 220));\n                drawSpellIcon(c, x + 22f, y + 22f, 7f, i, 255);\n                text(c, spellNames[i], x + 40f, y + 30f, 17f, Color.WHITE, Paint.Align.LEFT, true);''','loadout icon')
rep('''                drawGlowOrb(c, x + (boxW - 6f) * 0.5f, spellY + 20f, 7f, withAlpha(base, cdRemain <= 0.01f ? 245 : 120));''','''                drawGlowOrb(c, x + (boxW - 6f) * 0.5f, spellY + 20f, 10f, withAlpha(base, cdRemain <= 0.01f ? 255 : 120));\n                drawSpellIcon(c, x + (boxW - 6f) * 0.5f, spellY + 20f, 7f, sid, cdRemain <= 0.01f ? 255 : 150);''','hud icon')
rep('''                // boss\n                drawGlowOrb(c, e.x, e.y, e.rad * 1.4f, 0x33ff5c98);''','''                // boss anime aura\n                float pulse = 0.5f + 0.5f * (float)Math.sin(System.nanoTime() * 0.000000006);\n                drawGlowOrb(c, e.x, e.y, e.rad * (1.75f + pulse * 0.25f), 0x55ff5c98);\n                p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(2.5f); p.setColor(0x88ff8ab0);\n                c.drawCircle(e.x, e.y, e.rad * (1.18f + pulse * 0.08f), p);\n                p.setStyle(Paint.Style.FILL);\n                drawGlowOrb(c, e.x, e.y, e.rad * 1.4f, 0x33ff5c98);''','boss aura')
rep('''            // eyes\n            p.setColor(0xff1a1d2e);\n            c.drawCircle(x - 4f*s, cy - 22f*s, 1.4f*s, p);\n            c.drawCircle(x + 4f*s, cy - 22f*s, 1.4f*s, p);\n            p.setColor(fem ? 0xffd14b9e : 0xff3f91de);\n            c.drawCircle(x - 4f*s, cy - 22f*s, 0.7f*s, p);\n            c.drawCircle(x + 4f*s, cy - 22f*s, 0.7f*s, p);''','''            // anime eyes\n            p.setColor(0xffffffff);\n            c.drawOval(new RectF(x - 7f*s, cy - 26f*s, x - 1f*s, cy - 20f*s), p);\n            c.drawOval(new RectF(x + 1f*s, cy - 26f*s, x + 7f*s, cy - 20f*s), p);\n            p.setColor(fem ? 0xffd14b9e : 0xff3f91de);\n            c.drawCircle(x - 4f*s, cy - 23f*s, 2.0f*s, p);\n            c.drawCircle(x + 4f*s, cy - 23f*s, 2.0f*s, p);\n            p.setColor(0xff171923);\n            c.drawCircle(x - 4f*s, cy - 23f*s, 1.0f*s, p);\n            c.drawCircle(x + 4f*s, cy - 23f*s, 1.0f*s, p);\n            p.setColor(0xffffffff);\n            c.drawCircle(x - 4.7f*s, cy - 23.7f*s, 0.5f*s, p);\n            c.drawCircle(x + 3.3f*s, cy - 23.7f*s, 0.5f*s, p);''','anime eyes')
rep('''        void drawGlowOrb(Canvas c, float x, float y, float r, int color) {''','''        void drawSpellIcon(Canvas c, float x, float y, float r, int spellId, int alpha) {\n            int col = withAlpha(spellColor(spellId), alpha);\n            p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(Math.max(1.5f, r * 0.22f)); p.setColor(col);\n            if (spellId == SPELL_ARC) {\n                c.drawCircle(x, y, r * 0.72f, p); c.drawLine(x-r*.9f,y,x+r*.9f,y,p); c.drawLine(x,y-r*.9f,x,y+r*.9f,p);\n            } else if (spellId == SPELL_FIRE) {\n                Path f=new Path(); f.moveTo(x,y-r); f.quadTo(x-r*.9f,y-r*.1f,x-r*.15f,y+r); f.quadTo(x+r*.9f,y+r*.2f,x+r*.35f,y-r*.45f); f.quadTo(x+r*.05f,y-r*.1f,x,y-r); c.drawPath(f,p);\n            } else if (spellId == SPELL_FROST) {\n                for(int i=0;i<3;i++){float a=(float)(i*Math.PI/3.0);float dx=(float)Math.cos(a)*r,dy=(float)Math.sin(a)*r;c.drawLine(x-dx,y-dy,x+dx,y+dy,p);}\n            } else if (spellId == SPELL_CHAIN) {\n                Path z=new Path(); z.moveTo(x-r*.45f,y-r); z.lineTo(x+r*.05f,y-r*.15f); z.lineTo(x-r*.12f,y-r*.15f); z.lineTo(x+r*.45f,y+r); c.drawPath(z,p);\n            } else if (spellId == SPELL_WIND) {\n                c.drawArc(new RectF(x-r,y-r*.7f,x+r,y+r*.7f),205,235,false,p); c.drawArc(new RectF(x-r*.8f,y-r*.35f,x+r*.8f,y+r*.35f),210,225,false,p);\n            } else {\n                c.drawCircle(x,y,r*.75f,p); for(int i=0;i<6;i++){float a=(float)(i*Math.PI*2/6.0);c.drawLine(x+(float)Math.cos(a)*r*.85f,y+(float)Math.sin(a)*r*.85f,x+(float)Math.cos(a)*r*1.25f,y+(float)Math.sin(a)*r*1.25f,p);}\n            }\n            p.setStyle(Paint.Style.FILL);\n        }\n\n        void drawCastSigil(Canvas c, float x, float y, int spellId, float strength) {\n            float r=34f+(1f-strength)*18f; int col=spellColor(spellId);\n            drawGlowOrb(c,x,y,r*1.15f,withAlpha(col,(int)(90*strength)));\n            p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(2.2f); p.setColor(withAlpha(col,(int)(210*strength)));\n            c.drawCircle(x,y,r,p); c.drawCircle(x,y,r*.68f,p);\n            for(int i=0;i<6;i++){float a=(float)(i*Math.PI*2/6.0+System.nanoTime()*0.000000002);float x1=x+(float)Math.cos(a)*r*.72f,y1=y+(float)Math.sin(a)*r*.72f;float x2=x+(float)Math.cos(a)*r,y2=y+(float)Math.sin(a)*r;c.drawLine(x1,y1,x2,y2,p);}\n            p.setStyle(Paint.Style.FILL); drawSpellIcon(c,x,y,9f,spellId,(int)(255*strength));\n        }\n\n        void drawGlowOrb(Canvas c, float x, float y, float r, int color) {''','helpers')
p.write_text(s)
print('v1.8 patch applied')
